-- Fitness & Workout Platform — initial migration
-- Generated by hand from prisma/schema.prisma (single source of truth).
-- Do NOT run automatically; apply with `prisma migrate deploy` when ready.

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- CreateEnum: Role
CREATE TYPE "role_enum" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'TRAINER', 'NUTRITIONIST', 'MEMBER');

-- CreateEnum: SubscriptionType
CREATE TYPE "subscription_type_enum" AS ENUM ('FREE', 'PREMIUM', 'TRAINER_PRO', 'NUTRITION_PRO', 'ENTERPRISE');

-- CreateEnum: Sex
CREATE TYPE "sex_enum" AS ENUM ('MALE', 'FEMALE', 'OTHER');

-- CreateEnum: Units
CREATE TYPE "units_enum" AS ENUM ('METRIC', 'IMPERIAL');

-- CreateEnum: GoalType
CREATE TYPE "goal_type_enum" AS ENUM ('WEIGHT_LOSS', 'MUSCLE_GAIN', 'ENDURANCE', 'FLEXIBILITY', 'GENERAL_FITNESS', 'ATHLETIC_PERFORMANCE', 'MAINTENANCE');

-- CreateEnum: ExperienceLevel
CREATE TYPE "experience_level_enum" AS ENUM ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ATHLETE');

-- CreateEnum: Difficulty
CREATE TYPE "difficulty_enum" AS ENUM ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT');

-- CreateEnum: ExerciseType
CREATE TYPE "ExerciseType" AS ENUM ('STRENGTH', 'CARDIO', 'FLEXIBILITY', 'BALANCE', 'HIIT', 'PLYOMETRIC', 'SPORT');

-- CreateEnum: WorkoutSection
CREATE TYPE "WorkoutSection" AS ENUM ('WARMUP', 'MAIN', 'COOLDOWN');

-- CreateEnum: RepScheme
CREATE TYPE "RepScheme" AS ENUM ('STRAIGHT', 'PYRAMID', 'DROP_SETS', 'AMRAP', 'EMOM', 'TABATA', 'CUSTOM');

-- CreateEnum: Visibility
CREATE TYPE "Visibility" AS ENUM ('PRIVATE', 'PUBLIC', 'CLIENTS_ONLY');

-- CreateEnum: SessionStatus
CREATE TYPE "SessionStatus" AS ENUM ('ACTIVE', 'PAUSED', 'COMPLETED', 'PARTIAL', 'ABANDONED');

-- CreateEnum: CardioType
CREATE TYPE "CardioType" AS ENUM ('RUNNING', 'CYCLING', 'SWIMMING', 'WALKING', 'ROWING', 'ELLIPTICAL', 'JUMP_ROPE', 'STAIR_CLIMB', 'HIKING', 'CUSTOM');

-- CreateEnum: MealSlot
CREATE TYPE "MealSlot" AS ENUM ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'PRE_WORKOUT', 'POST_WORKOUT');

-- CreateEnum: PlanFrequency
CREATE TYPE "PlanFrequency" AS ENUM ('DAILY', 'WEEKLY');

-- CreateEnum: DietaryPreference
CREATE TYPE "DietaryPreference" AS ENUM ('STANDARD', 'VEGETARIAN', 'VEGAN', 'GLUTEN_FREE', 'DAIRY_FREE', 'KETO', 'PALEO', 'HALAL', 'KOSHER', 'CUSTOM');

-- CreateEnum: ProgramStatus
CREATE TYPE "ProgramStatus" AS ENUM ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', 'ARCHIVED');

-- CreateEnum: EnrollmentStatus
CREATE TYPE "EnrollmentStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'PAUSED', 'DROPPED');

-- CreateEnum: PostType
CREATE TYPE "PostType" AS ENUM ('WORKOUT', 'PROGRESS_PHOTO', 'ACHIEVEMENT', 'TIPS', 'ROUTE', 'CARDIO');

-- CreateEnum: CommentTarget
CREATE TYPE "CommentTarget" AS ENUM ('POST', 'GROUP_DISCUSSION');

-- CreateEnum: ActivityType
CREATE TYPE "ActivityType" AS ENUM ('WORKOUT', 'CARDIO', 'REST', 'LIVE_CLASS', 'TRAINER_SESSION');

-- CreateEnum: ScheduledStatus
CREATE TYPE "ScheduledStatus" AS ENUM ('PLANNED', 'COMPLETED', 'MISSED', 'RESCHEDULED', 'SKIPPED', 'REST_DAY');

-- CreateEnum: ChallengeType
CREATE TYPE "ChallengeType" AS ENUM ('STREAK', 'VOLUME', 'DISTANCE', 'STEPS', 'CALORIES', 'CUSTOM');

-- CreateEnum: ChallengeScope
CREATE TYPE "ChallengeScope" AS ENUM ('PLATFORM', 'TRAINER', 'COMMUNITY', 'TEAM', 'CORPORATE');

-- CreateEnum: LeaderboardPeriod
CREATE TYPE "LeaderboardPeriod" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'ALL_TIME');

-- CreateEnum: LiveClassStatus
CREATE TYPE "LiveClassStatus" AS ENUM ('SCHEDULED', 'LIVE', 'COMPLETED', 'CANCELLED');

-- CreateEnum: TrainerSessionType
CREATE TYPE "TrainerSessionType" AS ENUM ('VIDEO_CALL', 'IN_PERSON', 'PROGRAM_REVIEW', 'NUTRITION_COACHING');

-- CreateEnum: BookingStatus
CREATE TYPE "BookingStatus" AS ENUM ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW');

-- CreateEnum: VerificationStatus
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum: RequestStatus
CREATE TYPE "RequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum: NotificationType
CREATE TYPE "NotificationType" AS ENUM ('WORKOUT_REMINDER', 'STREAK_AT_RISK', 'PR_BROKEN', 'ACHIEVEMENT_UNLOCKED', 'CHALLENGE_UPDATE', 'CLASS_STARTING', 'NEW_FOLLOWER', 'KUDOS', 'COMMENT', 'TRAINER_MESSAGE', 'BOOKING_CONFIRMED', 'WEEKLY_REPORT', 'MEAL_REMINDER', 'WATER_REMINDER', 'PROGRAM_DAY_COMPLETE', 'PROGRAM_COMPLETED', 'NEW_PROGRAM', 'WEIGHT_GOAL', 'SUBSCRIPTION', 'SYSTEM');

-- CreateEnum: PaymentType
CREATE TYPE "PaymentType" AS ENUM ('SUBSCRIPTION', 'PROGRAM_PURCHASE', 'SESSION_BOOKING', 'LIVE_CLASS', 'PAYOUT', 'REFUND');

-- CreateEnum: PaymentStatus
CREATE TYPE "PaymentStatus" AS ENUM ('PROCESSING', 'SUCCEEDED', 'FAILED', 'REFUNDED');

-- CreateEnum: StripeSubscriptionStatus
CREATE TYPE "StripeSubscriptionStatus" AS ENUM ('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIALING', 'INCOMPLETE');

-- CreateEnum: AIFeature
CREATE TYPE "AIFeature" AS ENUM ('WORKOUT_PLAN', 'MEAL_PLAN', 'COACH_CHAT', 'FORM_CHECKER', 'PROGRESS_ANALYZER', 'INJURY_RISK', 'CALORIE_ESTIMATOR', 'FOOD_RECOGNITION', 'WORKOUT_MODIFICATION', 'PLATEAU_BUSTER', 'DELOAD_RECOMMENDATION', 'SUPPLEMENT_ADVISOR', 'RECOVERY_OPTIMIZER', 'STRENGTH_PREDICTOR', 'CARDIO_OPTIMIZER', 'ACCOUNTABILITY_COACH', 'ANNUAL_WRAP', 'MOTIVATIONAL_QUOTE', 'EXERCISE_ALTERNATIVES');

-- CreateEnum: WearableSource
CREATE TYPE "WearableSource" AS ENUM ('APPLE_HEALTH', 'GOOGLE_FIT', 'GARMIN_CSV', 'POLAR_CSV', 'FITBIT_CSV', 'MANUAL');

-- CreateEnum: WearableDataType
CREATE TYPE "WearableDataType" AS ENUM ('STEPS', 'HEART_RATE', 'SLEEP', 'ACTIVE_CALORIES', 'WORKOUT');

-- CreateEnum: GroupVisibility
CREATE TYPE "GroupVisibility" AS ENUM ('OPEN', 'CLOSED', 'PRIVATE');

-- CreateEnum: PRType
CREATE TYPE "PRType" AS ENUM ('MAX_WEIGHT', 'MAX_REPS', 'MAX_VOLUME', 'EST_1RM');

-- CreateEnum: BodyGoalType
CREATE TYPE "BodyGoalType" AS ENUM ('TARGET_WEIGHT', 'TARGET_BODY_FAT', 'TARGET_MEASUREMENT');

-- CreateEnum: CertificateType
CREATE TYPE "CertificateType" AS ENUM ('PROGRAM_COMPLETION', 'CHALLENGE_COMPLETION', 'MILESTONE');

-- CreateTable: User
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "clerk_user_id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "username" TEXT,
    "displayName" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "avatarUrl" TEXT,
    "bio" TEXT,
    "role" "role_enum" NOT NULL DEFAULT 'MEMBER',
    "subscriptionType" "subscription_type_enum" NOT NULL DEFAULT 'FREE',
    "onboarded" BOOLEAN NOT NULL DEFAULT false,
    "isBanned" BOOLEAN NOT NULL DEFAULT false,
    "units" "units_enum" NOT NULL DEFAULT 'METRIC',
    "language" TEXT NOT NULL DEFAULT 'en',
    "profileVisibility" "Visibility" NOT NULL DEFAULT 'PUBLIC',
    "workoutVisibility" "Visibility" NOT NULL DEFAULT 'PUBLIC',
    "statsVisibility" "Visibility" NOT NULL DEFAULT 'PRIVATE',
    "notification_prefs" JSONB NOT NULL DEFAULT '{}',
    "xpPoints" INTEGER NOT NULL DEFAULT 0,
    "level" INTEGER NOT NULL DEFAULT 1,
    "streakCurrent" INTEGER NOT NULL DEFAULT 0,
    "streakLongest" INTEGER NOT NULL DEFAULT 0,
    "lastWorkoutAt" TIMESTAMP(3),
    "streakFreezesUsed" INTEGER NOT NULL DEFAULT 0,
    "goal" "goal_type_enum",
    "experienceLevel" "experience_level_enum",
    "activityLevel" TEXT,
    "sex" "sex_enum",
    "birthDate" TIMESTAMP(3),
    "height_cm" DECIMAL(5,1),
    "weight_kg" DECIMAL(5,1),
    "target_weight_kg" DECIMAL(5,1),
    "preferred_types" TEXT[],
    "equipment" TEXT[],
    "injuries" TEXT[],
    "workout_days_week" INTEGER,
    "preferred_duration" INTEGER,
    "stripe_customer_id" TEXT,
    "lastActiveAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex (unique) for User
CREATE UNIQUE INDEX "users_clerk_user_id_key" ON "users"("clerk_user_id");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_username_key" ON "users"("username") WHERE "username" IS NOT NULL;
CREATE UNIQUE INDEX "users_stripe_customer_id_key" ON "users"("stripe_customer_id") WHERE "stripe_customer_id" IS NOT NULL;

-- CreateIndex for User
CREATE INDEX "users_role_idx" ON "users"("role");
CREATE INDEX "users_subscriptionType_idx" ON "users"("subscriptionType");
CREATE INDEX "users_streakCurrent_idx" ON "users"("streakCurrent");
CREATE INDEX "users_createdAt_idx" ON "users"("createdAt");

-- CreateTable: FitnessProfile
CREATE TABLE "fitness_profiles" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "goal" "goal_type_enum" NOT NULL DEFAULT 'GENERAL_FITNESS',
    "experienceLevel" "experience_level_enum" NOT NULL DEFAULT 'BEGINNER',
    "focusAreas" TEXT[],
    "equipment" TEXT[],
    "workoutDays" INTEGER,
    "sessionDuration" INTEGER,
    "limitations" TEXT[],
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "fitness_profiles_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "fitness_profiles_user_id_key" ON "fitness_profiles"("user_id");

-- CreateTable: Permission
CREATE TABLE "permissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "permissions_key_key" ON "permissions"("key");

-- CreateTable: RolePermission
CREATE TABLE "role_permissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "role" "role_enum" NOT NULL,
    "permission_id" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "role_permissions_role_permission_id_key" ON "role_permissions"("role", "permission_id");

-- CreateTable: Exercise
CREATE TABLE "exercises" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "exerciseType" "ExerciseType" NOT NULL DEFAULT 'STRENGTH',
    "difficulty" "difficulty_enum" NOT NULL DEFAULT 'BEGINNER',
    "primaryMuscles" TEXT[],
    "secondaryMuscles" TEXT[],
    "equipment" TEXT[],
    "category" TEXT,
    "videoUrl" TEXT,
    "demoImages" TEXT[],
    "instructions" JSONB NOT NULL DEFAULT '[]',
    "tips" TEXT[],
    "common_mistakes" TEXT[],
    "variations" JSONB NOT NULL DEFAULT '{}',
    "muscles_diagram" JSONB,
    "met_value" DECIMAL(4,1),
    "rating_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "rating_count" INTEGER NOT NULL DEFAULT 0,
    "usage_count" INTEGER NOT NULL DEFAULT 0,
    "status" "RequestStatus" NOT NULL DEFAULT 'APPROVED',
    "is_community" BOOLEAN NOT NULL DEFAULT false,
    "submitted_by_id" UUID,
    "alternatives" TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "exercises_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "exercises_category_idx" ON "exercises"("category");
CREATE INDEX "exercises_exerciseType_idx" ON "exercises"("exerciseType");
CREATE INDEX "exercises_difficulty_idx" ON "exercises"("difficulty");
CREATE INDEX "exercises_status_idx" ON "exercises"("status");
CREATE INDEX "exercises_name_idx" ON "exercises"("name");

-- CreateTable: FavoriteExercise
CREATE TABLE "favorite_exercises" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "exercise_id" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "favorite_exercises_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "favorite_exercises_user_id_exercise_id_key" ON "favorite_exercises"("user_id", "exercise_id");
CREATE INDEX "favorite_exercises_user_id_idx" ON "favorite_exercises"("user_id");

-- CreateTable: ExerciseRating
CREATE TABLE "exercise_ratings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "exercise_id" UUID NOT NULL,
    "rating" INTEGER NOT NULL,
    "comment" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "exercise_ratings_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "exercise_ratings_user_id_exercise_id_key" ON "exercise_ratings"("user_id", "exercise_id");
CREATE INDEX "exercise_ratings_exercise_id_idx" ON "exercise_ratings"("exercise_id");

-- CreateTable: Workout
CREATE TABLE "workouts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" "ExerciseType",
    "difficulty" "difficulty_enum" NOT NULL DEFAULT 'INTERMEDIATE',
    "estimated_duration" INTEGER,
    "equipment" TEXT[],
    "target_muscles" TEXT[],
    "thumbnail_url" TEXT,
    "visibility" "Visibility" NOT NULL DEFAULT 'PRIVATE',
    "tags" TEXT[],
    "is_template" BOOLEAN NOT NULL DEFAULT false,
    "estimated_calories" INTEGER,
    "parent_workout_id" UUID,
    "use_count" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "workouts_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "workouts_user_id_idx" ON "workouts"("user_id");
CREATE INDEX "workouts_visibility_idx" ON "workouts"("visibility");
CREATE INDEX "workouts_is_template_idx" ON "workouts"("is_template");
CREATE INDEX "workouts_createdAt_idx" ON "workouts"("createdAt");

-- CreateTable: WorkoutExercise
CREATE TABLE "workout_exercises" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "workout_id" UUID NOT NULL,
    "exercise_id" UUID NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "sets" INTEGER NOT NULL DEFAULT 3,
    "reps" TEXT,
    "weight" DECIMAL(7,2),
    "duration_sec" INTEGER,
    "rest_sec" INTEGER NOT NULL DEFAULT 90,
    "rpe_target" INTEGER,
    "section" "WorkoutSection" NOT NULL DEFAULT 'MAIN',
    "notes" TEXT,
    "coachingCues" TEXT,
    "configuration" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workout_exercises_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "workout_exercises_workout_id_position_idx" ON "workout_exercises"("workout_id", "position");
CREATE INDEX "workout_exercises_exercise_id_idx" ON "workout_exercises"("exercise_id");

-- CreateTable: Program
CREATE TABLE "programs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "creator_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "goal" "goal_type_enum" NOT NULL DEFAULT 'GENERAL_FITNESS',
    "difficulty" "difficulty_enum" NOT NULL DEFAULT 'BEGINNER',
    "program_type" TEXT,
    "duration_weeks" INTEGER NOT NULL,
    "days_per_week" INTEGER NOT NULL,
    "equipment" TEXT[],
    "cover_image_url" TEXT,
    "trailer_video_url" TEXT,
    "price_cents" INTEGER NOT NULL DEFAULT 0,
    "currency" TEXT NOT NULL DEFAULT 'usd',
    "commission_pct" DECIMAL(5,2) NOT NULL DEFAULT 20,
    "status" "ProgramStatus" NOT NULL DEFAULT 'DRAFT',
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "is_ai_generated" BOOLEAN NOT NULL DEFAULT false,
    "assigned_client_ids" TEXT[],
    "enrollment_count" INTEGER NOT NULL DEFAULT 0,
    "completion_count" INTEGER NOT NULL DEFAULT 0,
    "revenue_cents" BIGINT NOT NULL DEFAULT 0,
    "rating_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "rating_count" INTEGER NOT NULL DEFAULT 0,
    "sales_count" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "programs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "programs_creator_id_idx" ON "programs"("creator_id");
CREATE INDEX "programs_status_idx" ON "programs"("status");
CREATE INDEX "programs_featured_idx" ON "programs"("featured");
CREATE INDEX "programs_goal_idx" ON "programs"("goal");
CREATE INDEX "programs_price_cents_idx" ON "programs"("price_cents");
CREATE INDEX "programs_createdAt_idx" ON "programs"("createdAt");

-- CreateTable: ProgramWorkout
CREATE TABLE "program_workouts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "program_id" UUID NOT NULL,
    "workout_id" UUID NOT NULL,
    "week" INTEGER NOT NULL,
    "day_of_week" INTEGER NOT NULL,
    "is_rest_day" BOOLEAN NOT NULL DEFAULT false,
    "progressionNote" TEXT,
    "position" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "program_workouts_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "program_workouts_program_id_week_day_of_week_workout_id_key" ON "program_workouts"("program_id", "week", "day_of_week", "workout_id");
CREATE INDEX "program_workouts_program_id_week_idx" ON "program_workouts"("program_id", "week");

-- CreateTable: ProgramEnrollment
CREATE TABLE "program_enrollments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "program_id" UUID NOT NULL,
    "status" "EnrollmentStatus" NOT NULL DEFAULT 'ACTIVE',
    "current_week" INTEGER NOT NULL DEFAULT 1,
    "progress_pct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "workouts_done" INTEGER NOT NULL DEFAULT 0,
    "total_workouts" INTEGER NOT NULL DEFAULT 0,
    "start_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "target_finish_date" TIMESTAMP(3),
    "completed_at" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "program_enrollments_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "program_enrollments_user_id_program_id_key" ON "program_enrollments"("user_id", "program_id");
CREATE INDEX "program_enrollments_program_id_status_idx" ON "program_enrollments"("program_id", "status");
CREATE INDEX "program_enrollments_user_id_status_idx" ON "program_enrollments"("user_id", "status");

-- CreateTable: ProgramReview
CREATE TABLE "program_reviews" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "program_id" UUID NOT NULL,
    "enrollment_id" UUID,
    "rating" INTEGER NOT NULL,
    "title" TEXT,
    "comment" TEXT,
    "helpful_count" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "program_reviews_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "program_reviews_user_id_program_id_key" ON "program_reviews"("user_id", "program_id");
CREATE INDEX "program_reviews_program_id_rating_idx" ON "program_reviews"("program_id", "rating");

-- CreateTable: Certificate
CREATE TABLE "certificates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "program_id" UUID,
    "type" "CertificateType" NOT NULL DEFAULT 'PROGRAM_COMPLETION',
    "title" TEXT NOT NULL,
    "pdf_url" TEXT,
    "issued_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "share_url" TEXT,

    CONSTRAINT "certificates_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "certificates_user_id_idx" ON "certificates"("user_id");


-- CreateTable: WorkoutSession
CREATE TABLE "workout_sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "workout_id" UUID,
    "program_id" UUID,
    "program_workout_id" UUID,
    "name" TEXT,
    "status" "SessionStatus" NOT NULL DEFAULT 'ACTIVE',
    "started_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMP(3),
    "paused_at" TIMESTAMP(3),
    "paused_total_ms" BIGINT NOT NULL DEFAULT 0,
    "duration_sec" INTEGER,
    "total_volume" BIGINT NOT NULL DEFAULT 0,
    "total_sets" INTEGER NOT NULL DEFAULT 0,
    "calories_burned" INTEGER,
    "avg_rpe" DECIMAL(3,1),
    "hr_avg" INTEGER,
    "hr_max" INTEGER,
    "rating" INTEGER,
    "felt_energy" INTEGER,
    "felt_soreness" INTEGER,
    "notes" TEXT,
    "summary" JSONB NOT NULL DEFAULT '{}',
    "auto_saved_at" TIMESTAMP(3),
    "pr_count" INTEGER NOT NULL DEFAULT 0,
    "is_shared" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "workout_sessions_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "workout_sessions_user_id_status_idx" ON "workout_sessions"("user_id", "status");
CREATE INDEX "workout_sessions_user_id_started_at_idx" ON "workout_sessions"("user_id", "started_at");
CREATE INDEX "workout_sessions_workout_id_idx" ON "workout_sessions"("workout_id");
CREATE INDEX "workout_sessions_createdAt_idx" ON "workout_sessions"("createdAt");

-- CreateTable: SessionLoggedSet
CREATE TABLE "session_logged_sets" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "session_id" UUID NOT NULL,
    "exercise_id" UUID NOT NULL,
    "set_number" INTEGER NOT NULL,
    "reps" INTEGER,
    "weight" DECIMAL(7,2),
    "duration_sec" INTEGER,
    "distance_m" INTEGER,
    "rpe" INTEGER,
    "hr_avg" INTEGER,
    "rest_sec" INTEGER,
    "notes" TEXT,
    "skipped" BOOLEAN NOT NULL DEFAULT false,
    "is_pr" BOOLEAN NOT NULL DEFAULT false,
    "logged_data" JSONB NOT NULL DEFAULT '{}',
    "logged_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "session_logged_sets_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "session_logged_sets_session_id_idx" ON "session_logged_sets"("session_id");
CREATE INDEX "session_logged_sets_exercise_id_logged_at_idx" ON "session_logged_sets"("exercise_id", "logged_at");

-- CreateTable: PersonalRecord
CREATE TABLE "personal_records" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "exercise_id" UUID NOT NULL,
    "max_weight" DECIMAL(7,2),
    "max_reps" INTEGER,
    "max_volume" BIGINT NOT NULL DEFAULT 0,
    "est_1rm" DECIMAL(7,2),
    "achieved_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "personal_records_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "personal_records_user_id_exercise_id_key" ON "personal_records"("user_id", "exercise_id");
CREATE INDEX "personal_records_user_id_idx" ON "personal_records"("user_id");

-- CreateTable: PRHistory
CREATE TABLE "pr_history" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "exercise_id" UUID NOT NULL,
    "record_id" UUID NOT NULL,
    "type" "PRType" NOT NULL,
    "value" DECIMAL(9,2) NOT NULL,
    "reps" INTEGER,
    "session_id" UUID,
    "achieved_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "pr_history_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "pr_history_user_id_exercise_id_idx" ON "pr_history"("user_id", "exercise_id");
CREATE INDEX "pr_history_achieved_at_idx" ON "pr_history"("achieved_at");

-- CreateTable: CardioSession
CREATE TABLE "cardio_sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "activity_type" "CardioType" NOT NULL DEFAULT 'RUNNING',
    "title" TEXT,
    "route_id" UUID,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "duration_sec" INTEGER NOT NULL,
    "distance_m" INTEGER,
    "calories" INTEGER,
    "avg_hr" INTEGER,
    "max_hr" INTEGER,
    "avg_pace_sec_km" INTEGER,
    "fastest_km_sec" INTEGER,
    "elevation_m" INTEGER,
    "laps" JSONB NOT NULL DEFAULT '[]',
    "hr_zones" JSONB NOT NULL DEFAULT '{}',
    "source" TEXT NOT NULL DEFAULT 'MANUAL',
    "notes" TEXT,
    "is_shared" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cardio_sessions_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "cardio_sessions_user_id_date_idx" ON "cardio_sessions"("user_id", "date");
CREATE INDEX "cardio_sessions_activity_type_idx" ON "cardio_sessions"("activity_type");

-- CreateTable: Route
CREATE TABLE "routes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "activity_type" "CardioType" NOT NULL DEFAULT 'RUNNING',
    "distance_m" INTEGER NOT NULL DEFAULT 0,
    "elevation_m" INTEGER,
    "points" JSONB NOT NULL DEFAULT '[]',
    "map_image_url" TEXT,
    "is_shared" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "routes_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "routes_user_id_idx" ON "routes"("user_id");

-- CreateTable: Food
CREATE TABLE "foods" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "brand" TEXT,
    "serving_size_g" DECIMAL(8,2),
    "serving_label" TEXT,
    "calories" INTEGER NOT NULL,
    "protein_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "carbs_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "fat_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "fiber_g" DECIMAL(7,2),
    "sugar_g" DECIMAL(7,2),
    "sodium_mg" DECIMAL(9,2),
    "saturated_fat_g" DECIMAL(7,2),
    "micros" JSONB NOT NULL DEFAULT '{}',
    "barcode" TEXT,
    "category" TEXT,
    "is_restaurant" BOOLEAN NOT NULL DEFAULT false,
    "verified" BOOLEAN NOT NULL DEFAULT true,
    "created_by_id" UUID,
    "use_count" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "foods_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "foods_name_idx" ON "foods"("name");
CREATE INDEX "foods_barcode_idx" ON "foods"("barcode");
CREATE INDEX "foods_category_idx" ON "foods"("category");
CREATE INDEX "foods_created_by_id_idx" ON "foods"("created_by_id");

-- CreateTable: FoodFavorite
CREATE TABLE "food_favorites" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "food_id" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "food_favorites_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "food_favorites_user_id_food_id_key" ON "food_favorites"("user_id", "food_id");

-- CreateTable: Recipe
CREATE TABLE "recipes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "servings" INTEGER NOT NULL DEFAULT 1,
    "calories" INTEGER NOT NULL DEFAULT 0,
    "protein_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "carbs_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "fat_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "dietary_tags" TEXT[],
    "instructions" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "recipes_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "recipes_user_id_idx" ON "recipes"("user_id");

-- CreateTable: RecipeIngredient
CREATE TABLE "recipe_ingredients" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "recipe_id" UUID NOT NULL,
    "food_id" UUID,
    "name" TEXT,
    "quantity" DECIMAL(9,3) NOT NULL,
    "unit" TEXT NOT NULL DEFAULT 'g',

    CONSTRAINT "recipe_ingredients_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "recipe_ingredients_recipe_id_idx" ON "recipe_ingredients"("recipe_id");

-- CreateTable: MealLogEntry
CREATE TABLE "meal_log_entries" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "slot" "MealSlot" NOT NULL DEFAULT 'SNACK',
    "food_id" UUID,
    "recipe_id" UUID,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "servings" DECIMAL(6,2) NOT NULL DEFAULT 1,
    "calories" INTEGER NOT NULL,
    "protein_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "carbs_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "fat_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "meal_name" TEXT,
    "ai_estimated" BOOLEAN NOT NULL DEFAULT false,
    "photo_url" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meal_log_entries_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "meal_log_entries_user_id_date_idx" ON "meal_log_entries"("user_id", "date");
CREATE INDEX "meal_log_entries_food_id_idx" ON "meal_log_entries"("food_id");

-- CreateTable: WaterLog
CREATE TABLE "water_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "amount_ml" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "water_logs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "water_logs_user_id_date_idx" ON "water_logs"("user_id", "date");

-- CreateTable: NutritionGoal
CREATE TABLE "nutrition_goals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "calorie_target" INTEGER NOT NULL,
    "protein_g" INTEGER NOT NULL,
    "carbs_g" INTEGER NOT NULL,
    "fat_g" INTEGER NOT NULL,
    "preset" "DietaryPreference",
    "calorie_cycling" JSONB NOT NULL DEFAULT '{}',
    "water_target_ml" INTEGER NOT NULL DEFAULT 3000,
    "tdee" INTEGER,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "nutrition_goals_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "nutrition_goals_user_id_key" ON "nutrition_goals"("user_id");

-- CreateTable: MealPlan
CREATE TABLE "meal_plans" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "creator_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "goal" "goal_type_enum" NOT NULL DEFAULT 'GENERAL_FITNESS',
    "dietary" "DietaryPreference" NOT NULL DEFAULT 'STANDARD',
    "frequency" "PlanFrequency" NOT NULL DEFAULT 'WEEKLY',
    "calories_per_day" INTEGER,
    "protein_g" INTEGER,
    "carbs_g" INTEGER,
    "fat_g" INTEGER,
    "allergies" TEXT[],
    "cuisine" TEXT,
    "is_ai_generated" BOOLEAN NOT NULL DEFAULT false,
    "day_config" JSONB NOT NULL DEFAULT '{}',
    "published" BOOLEAN NOT NULL DEFAULT false,
    "price_cents" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "meal_plans_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "meal_plans_creator_id_idx" ON "meal_plans"("creator_id");
CREATE INDEX "meal_plans_dietary_idx" ON "meal_plans"("dietary");

-- CreateTable: PlanMeal
CREATE TABLE "plan_meals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "plan_id" UUID NOT NULL,
    "slot" "MealSlot" NOT NULL,
    "day_index" INTEGER NOT NULL DEFAULT 1,
    "food_id" UUID,
    "recipe_id" UUID,
    "label" TEXT,
    "servings" DECIMAL(6,2) NOT NULL DEFAULT 1,
    "calories" INTEGER NOT NULL DEFAULT 0,
    "protein_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "carbs_g" DECIMAL(7,2) NOT NULL DEFAULT 0,
    "fat_g" DECIMAL(7,2) NOT NULL DEFAULT 0,

    CONSTRAINT "plan_meals_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "plan_meals_plan_id_day_index_idx" ON "plan_meals"("plan_id", "day_index");

-- CreateTable: MealPlanFollow
CREATE TABLE "meal_plan_follows" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "plan_id" UUID NOT NULL,
    "start_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meal_plan_follows_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "meal_plan_follows_user_id_plan_id_key" ON "meal_plan_follows"("user_id", "plan_id");

-- CreateTable: GroceryList
CREATE TABLE "grocery_lists" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "plan_id" UUID,
    "items" JSONB NOT NULL DEFAULT '[]',
    "pdf_url" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "grocery_lists_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "grocery_lists_user_id_idx" ON "grocery_lists"("user_id");


-- CreateTable: BodyStat
CREATE TABLE "body_stats" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "weight_kg" DECIMAL(5,1),
    "body_fat_pct" DECIMAL(4,1),
    "muscle_mass_kg" DECIMAL(5,1),
    "bmi" DECIMAL(4,1),
    "measurements" JSONB NOT NULL DEFAULT '{}',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "body_stats_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "body_stats_user_id_date_idx" ON "body_stats"("user_id", "date");

-- CreateTable: ProgressPhoto
CREATE TABLE "progress_photos" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "session_id" UUID,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "image_url" TEXT NOT NULL,
    "pose" TEXT,
    "weight_kg" DECIMAL(5,1),
    "body_fat_pct" DECIMAL(4,1),
    "is_before_after" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "progress_photos_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "progress_photos_user_id_date_idx" ON "progress_photos"("user_id", "date");

-- CreateTable: BodyStatGoal
CREATE TABLE "body_stat_goals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "type" "BodyGoalType" NOT NULL,
    "metric_key" TEXT NOT NULL,
    "start_value" DECIMAL(7,2) NOT NULL,
    "target_value" DECIMAL(7,2) NOT NULL,
    "current_value" DECIMAL(7,2),
    "target_date" TIMESTAMP(3),
    "achieved_at" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "body_stat_goals_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "body_stat_goals_user_id_type_idx" ON "body_stat_goals"("user_id", "type");

-- CreateTable: Achievement
CREATE TABLE "achievements" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "icon_url" TEXT,
    "category" TEXT,
    "criteria" JSONB NOT NULL DEFAULT '{}',
    "xp_reward" INTEGER NOT NULL DEFAULT 150,
    "rarity" TEXT NOT NULL DEFAULT 'COMMON',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "achievements_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "achievements_key_key" ON "achievements"("key");

-- CreateTable: UserAchievement
CREATE TABLE "user_achievements" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "achievement_id" UUID NOT NULL,
    "unlocked_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "progress_value" DECIMAL(9,2),

    CONSTRAINT "user_achievements_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "user_achievements_user_id_achievement_id_key" ON "user_achievements"("user_id", "achievement_id");
CREATE INDEX "user_achievements_user_id_idx" ON "user_achievements"("user_id");

-- CreateTable: Follow
CREATE TABLE "follows" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "follower_id" UUID NOT NULL,
    "following_id" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "follows_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "follows_follower_id_following_id_key" ON "follows"("follower_id", "following_id");
CREATE INDEX "follows_following_id_idx" ON "follows"("following_id");

-- CreateTable: Post
CREATE TABLE "posts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "type" "PostType" NOT NULL,
    "session_id" UUID,
    "cardio_id" UUID,
    "route_id" UUID,
    "photo_id" UUID,
    "group_id" UUID,
    "content" TEXT,
    "media_urls" TEXT[],
    "stats" JSONB NOT NULL DEFAULT '{}',
    "hashtags" TEXT[],
    "mentions" TEXT[],
    "kudos_count" INTEGER NOT NULL DEFAULT 0,
    "comments_count" INTEGER NOT NULL DEFAULT 0,
    "is_public" BOOLEAN NOT NULL DEFAULT true,
    "flagged" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "posts_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "posts_user_id_createdAt_idx" ON "posts"("user_id", "createdAt");
CREATE INDEX "posts_group_id_idx" ON "posts"("group_id");
CREATE INDEX "posts_type_idx" ON "posts"("type");
CREATE INDEX "posts_createdAt_idx" ON "posts"("createdAt");

-- CreateTable: Comment
CREATE TABLE "comments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "target_type" "CommentTarget" NOT NULL DEFAULT 'POST',
    "post_id" UUID,
    "discussion_id" UUID,
    "parent_id" UUID,
    "content" TEXT NOT NULL,
    "mentions" TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "comments_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "comments_post_id_idx" ON "comments"("post_id");
CREATE INDEX "comments_discussion_id_idx" ON "comments"("discussion_id");

-- CreateTable: Kudos
CREATE TABLE "kudos" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "post_id" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kudos_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "kudos_user_id_post_id_key" ON "kudos"("user_id", "post_id");
CREATE INDEX "kudos_post_id_idx" ON "kudos"("post_id");

-- CreateTable: Group
CREATE TABLE "groups" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "cover_url" TEXT,
    "visibility" "GroupVisibility" NOT NULL DEFAULT 'OPEN',
    "category" TEXT,
    "created_by" UUID NOT NULL,
    "member_count" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "groups_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "groups_slug_key" ON "groups"("slug");
CREATE INDEX "groups_category_idx" ON "groups"("category");

-- CreateTable: GroupMember
CREATE TABLE "group_members" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "group_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'MEMBER',
    "joined_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "group_members_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "group_members_group_id_user_id_key" ON "group_members"("group_id", "user_id");
CREATE INDEX "group_members_user_id_idx" ON "group_members"("user_id");

-- CreateTable: GroupDiscussion
CREATE TABLE "group_discussions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "group_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT,
    "pinned" BOOLEAN NOT NULL DEFAULT false,
    "reply_count" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "group_discussions_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "group_discussions_group_id_createdAt_idx" ON "group_discussions"("group_id", "createdAt");

-- CreateTable: Block
CREATE TABLE "blocks" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "blocker_id" UUID NOT NULL,
    "blocked_id" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "blocks_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "blocks_blocker_id_blocked_id_key" ON "blocks"("blocker_id", "blocked_id");

-- CreateTable: ContentReport
CREATE TABLE "content_reports" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "reporter_id" UUID NOT NULL,
    "target_type" TEXT NOT NULL,
    "target_id" UUID NOT NULL,
    "post_id" UUID,
    "reason" TEXT NOT NULL,
    "status" "RequestStatus" NOT NULL DEFAULT 'PENDING',
    "reviewed_by" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "content_reports_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "content_reports_status_idx" ON "content_reports"("status");

-- CreateTable: TrainerProfile
CREATE TABLE "trainer_profiles" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "bio" TEXT,
    "specializations" TEXT[],
    "certifications" JSONB NOT NULL DEFAULT '[]',
    "years_experience" INTEGER,
    "languages" TEXT[],
    "hourly_rate_cents" INTEGER NOT NULL DEFAULT 5000,
    "currency" TEXT NOT NULL DEFAULT 'usd',
    "verification_status" "VerificationStatus" NOT NULL DEFAULT 'PENDING',
    "verified_by_id" UUID,
    "stripe_connect_account_id" TEXT,
    "rating_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "rating_count" INTEGER NOT NULL DEFAULT 0,
    "client_count" INTEGER NOT NULL DEFAULT 0,
    "sessions_done" INTEGER NOT NULL DEFAULT 0,
    "total_earnings_cents" BIGINT NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "trainer_profiles_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "trainer_profiles_user_id_key" ON "trainer_profiles"("user_id");
CREATE UNIQUE INDEX "trainer_profiles_stripe_connect_account_id_key" ON "trainer_profiles"("stripe_connect_account_id") WHERE "stripe_connect_account_id" IS NOT NULL;
CREATE INDEX "trainer_profiles_verification_status_idx" ON "trainer_profiles"("verification_status");
CREATE INDEX "trainer_profiles_rating_avg_idx" ON "trainer_profiles"("rating_avg");
CREATE INDEX "trainer_profiles_hourly_rate_cents_idx" ON "trainer_profiles"("hourly_rate_cents");

-- CreateTable: TrainerAvailability
CREATE TABLE "trainer_availability" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "trainer_id" UUID NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "start_time" TIMESTAMP(3) NOT NULL,
    "end_time" TIMESTAMP(3) NOT NULL,
    "session_types" TEXT[],
    "booked" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "trainer_availability_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "trainer_availability_trainer_id_date_idx" ON "trainer_availability"("trainer_id", "date");

-- CreateTable: TrainerSessionBooking
CREATE TABLE "trainer_session_bookings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "trainer_id" UUID NOT NULL,
    "client_id" UUID NOT NULL,
    "availability_id" UUID,
    "session_type" "TrainerSessionType" NOT NULL DEFAULT 'VIDEO_CALL',
    "scheduled_at" TIMESTAMP(3) NOT NULL,
    "duration_min" INTEGER NOT NULL DEFAULT 60,
    "status" "BookingStatus" NOT NULL DEFAULT 'PENDING',
    "price_cents" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'usd',
    "stripe_payment_intent_id" TEXT,
    "pre_session_notes" TEXT,
    "post_session_notes" TEXT,
    "homework" JSONB NOT NULL DEFAULT '[]',
    "rating" INTEGER,
    "review" TEXT,
    "video_room_id" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "trainer_session_bookings_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "trainer_session_bookings_stripe_payment_intent_id_key" ON "trainer_session_bookings"("stripe_payment_intent_id") WHERE "stripe_payment_intent_id" IS NOT NULL;
CREATE INDEX "trainer_session_bookings_trainer_id_status_idx" ON "trainer_session_bookings"("trainer_id", "status");
CREATE INDEX "trainer_session_bookings_client_id_status_idx" ON "trainer_session_bookings"("client_id", "status");
CREATE INDEX "trainer_session_bookings_scheduled_at_idx" ON "trainer_session_bookings"("scheduled_at");

-- CreateTable: TrainerClient
CREATE TABLE "trainer_clients" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "trainer_id" UUID NOT NULL,
    "client_user_id" UUID NOT NULL,
    "share_workouts" BOOLEAN NOT NULL DEFAULT false,
    "share_nutrition" BOOLEAN NOT NULL DEFAULT false,
    "share_body_stats" BOOLEAN NOT NULL DEFAULT false,
    "assigned_program_ids" TEXT[],
    "granted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "trainer_clients_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "trainer_clients_trainer_id_client_user_id_key" ON "trainer_clients"("trainer_id", "client_user_id");
CREATE INDEX "trainer_clients_client_user_id_idx" ON "trainer_clients"("client_user_id");

-- CreateTable: TrainerMessage
CREATE TABLE "trainer_messages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID,
    "sender_id" UUID NOT NULL,
    "receiver_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "read_at" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "trainer_messages_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "trainer_messages_booking_id_createdAt_idx" ON "trainer_messages"("booking_id", "createdAt");
CREATE INDEX "trainer_messages_receiver_id_read_at_idx" ON "trainer_messages"("receiver_id", "read_at");

-- CreateTable: LiveClass
CREATE TABLE "live_classes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "trainer_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "classType" TEXT NOT NULL,
    "duration_min" INTEGER NOT NULL DEFAULT 45,
    "scheduled_at" TIMESTAMP(3) NOT NULL,
    "status" "LiveClassStatus" NOT NULL DEFAULT 'SCHEDULED',
    "max_participants" INTEGER NOT NULL DEFAULT 50,
    "price_cents" INTEGER NOT NULL DEFAULT 0,
    "currency" TEXT NOT NULL DEFAULT 'usd',
    "cover_image_url" TEXT,
    "recording_url" TEXT,
    "hls_playlist_url" TEXT,
    "room_id" TEXT NOT NULL,
    "attendee_count" INTEGER NOT NULL DEFAULT 0,
    "waitlist_count" INTEGER NOT NULL DEFAULT 0,
    "rating_avg" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "rating_count" INTEGER NOT NULL DEFAULT 0,
    "engagement" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "live_classes_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "live_classes_room_id_key" ON "live_classes"("room_id");
CREATE INDEX "live_classes_trainer_id_idx" ON "live_classes"("trainer_id");
CREATE INDEX "live_classes_scheduled_at_status_idx" ON "live_classes"("scheduled_at", "status");
CREATE INDEX "live_classes_classType_idx" ON "live_classes"("classType");

-- CreateTable: ClassEnrollment
CREATE TABLE "class_enrollments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "class_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ENROLLED',
    "paid_cents" INTEGER NOT NULL DEFAULT 0,
    "is_waitlist" BOOLEAN NOT NULL DEFAULT false,
    "rating" INTEGER,
    "attended_for" INTEGER,
    "enrolled_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "class_enrollments_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "class_enrollments_class_id_user_id_key" ON "class_enrollments"("class_id", "user_id");
CREATE INDEX "class_enrollments_user_id_status_idx" ON "class_enrollments"("user_id", "status");

-- CreateTable: ClassChatMessage
CREATE TABLE "class_chat_messages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "class_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "reaction" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "class_chat_messages_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "class_chat_messages_class_id_createdAt_idx" ON "class_chat_messages"("class_id", "createdAt");


-- CreateTable: Challenge
CREATE TABLE "challenges" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "creator_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "type" "ChallengeType" NOT NULL DEFAULT 'STREAK',
    "scope" "ChallengeScope" NOT NULL DEFAULT 'PLATFORM',
    "group_id" UUID,
    "corporate_org_id" UUID,
    "rules_config" JSONB NOT NULL DEFAULT '{}',
    "goal_value" DECIMAL(12,2) NOT NULL,
    "goal_unit" TEXT NOT NULL DEFAULT 'reps',
    "start_date" TIMESTAMP(3) NOT NULL,
    "end_date" TIMESTAMP(3) NOT NULL,
    "prize" TEXT,
    "is_team_based" BOOLEAN NOT NULL DEFAULT false,
    "max_teams" INTEGER,
    "participant_count" INTEGER NOT NULL DEFAULT 0,
    "completion_count" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "auto_generated" BOOLEAN NOT NULL DEFAULT false,
    "milestones" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "challenges_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "challenges_active_end_date_idx" ON "challenges"("active", "end_date");
CREATE INDEX "challenges_type_idx" ON "challenges"("type");
CREATE INDEX "challenges_scope_idx" ON "challenges"("scope");

-- CreateTable: ChallengeEnrollment
CREATE TABLE "challenge_enrollments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "challenge_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "team_id" UUID,
    "progress_value" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "rank" INTEGER,
    "milestones_hit" TEXT[],
    "completed_at" TIMESTAMP(3),
    "joined_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "challenge_enrollments_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "challenge_enrollments_challenge_id_user_id_key" ON "challenge_enrollments"("challenge_id", "user_id");
CREATE INDEX "challenge_enrollments_challenge_id_progress_value_idx" ON "challenge_enrollments"("challenge_id", "progress_value");

-- CreateTable: ChallengeMilestone
CREATE TABLE "challenge_milestones" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "challenge_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "label" TEXT NOT NULL,
    "reached_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "challenge_milestones_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "challenge_milestones_challenge_id_user_id_idx" ON "challenge_milestones"("challenge_id", "user_id");

-- CreateTable: ChallengeTeam
CREATE TABLE "challenge_teams" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "challenge_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "total_score" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "rank" INTEGER,

    CONSTRAINT "challenge_teams_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "challenge_teams_challenge_id_name_key" ON "challenge_teams"("challenge_id", "name");

-- CreateTable: ChallengeTeamMember
CREATE TABLE "challenge_team_members" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "team_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,

    CONSTRAINT "challenge_team_members_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "challenge_team_members_team_id_user_id_key" ON "challenge_team_members"("team_id", "user_id");

-- CreateTable: LeaderboardSnapshot
CREATE TABLE "leaderboard_snapshots" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "scope" TEXT NOT NULL,
    "scope_id" UUID,
    "period" "LeaderboardPeriod" NOT NULL DEFAULT 'WEEKLY',
    "entries" JSONB NOT NULL DEFAULT '[]',
    "computed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "leaderboard_snapshots_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "leaderboard_snapshots_scope_scope_id_period_idx" ON "leaderboard_snapshots"("scope", "scope_id", "period");

-- CreateTable: ScheduledItem
CREATE TABLE "scheduled_items" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "activity_type" "ActivityType" NOT NULL,
    "workout_id" UUID,
    "program_id" UUID,
    "class_id" UUID,
    "challenge_id" UUID,
    "booking_id" UUID,
    "enrollment_id" UUID,
    "status" "ScheduledStatus" NOT NULL DEFAULT 'PLANNED',
    "rescheduled_from" TIMESTAMP(3),
    "reminder_sent" BOOLEAN NOT NULL DEFAULT false,
    "is_deload" BOOLEAN NOT NULL DEFAULT false,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "scheduled_items_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "scheduled_items_user_id_date_idx" ON "scheduled_items"("user_id", "date");
CREATE INDEX "scheduled_items_status_idx" ON "scheduled_items"("status");

-- CreateTable: Notification
CREATE TABLE "notifications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "type" "NotificationType" NOT NULL DEFAULT 'SYSTEM',
    "title" TEXT NOT NULL,
    "body" TEXT,
    "data" JSONB NOT NULL DEFAULT '{}',
    "read_at" TIMESTAMP(3),
    "delivered" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "notifications_user_id_read_at_idx" ON "notifications"("user_id", "read_at");
CREATE INDEX "notifications_user_id_createdAt_idx" ON "notifications"("user_id", "createdAt");

-- CreateTable: DeviceToken
CREATE TABLE "device_tokens" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "token" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "device_tokens_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "device_tokens_token_key" ON "device_tokens"("token");
CREATE INDEX "device_tokens_user_id_idx" ON "device_tokens"("user_id");

-- CreateTable: WebPushSubscription
CREATE TABLE "web_push_subscriptions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "endpoint" TEXT NOT NULL,
    "keys" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "web_push_subscriptions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "web_push_subscriptions_endpoint_key" ON "web_push_subscriptions"("endpoint");
CREATE INDEX "web_push_subscriptions_user_id_idx" ON "web_push_subscriptions"("user_id");

-- CreateTable: Subscription
CREATE TABLE "subscriptions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "plan" "subscription_type_enum" NOT NULL,
    "stripe_subscription_id" TEXT NOT NULL,
    "stripe_price_id" TEXT,
    "status" "StripeSubscriptionStatus" NOT NULL DEFAULT 'INCOMPLETE',
    "current_period_end" TIMESTAMP(3) NOT NULL,
    "cancel_at_period_end" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "subscriptions_stripe_subscription_id_key" ON "subscriptions"("stripe_subscription_id");
CREATE INDEX "subscriptions_user_id_status_idx" ON "subscriptions"("user_id", "status");

-- CreateTable: Payment
CREATE TABLE "payments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "type" "PaymentType" NOT NULL,
    "status" "PaymentStatus" NOT NULL DEFAULT 'PROCESSING',
    "amount_cents" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'usd',
    "platform_fee_cents" INTEGER NOT NULL DEFAULT 0,
    "recipient_user_id" UUID,
    "stripe_payment_intent_id" TEXT,
    "program_id" UUID,
    "booking_id" UUID,
    "class_id" UUID,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "payments_stripe_payment_intent_id_key" ON "payments"("stripe_payment_intent_id") WHERE "stripe_payment_intent_id" IS NOT NULL;
CREATE INDEX "payments_user_id_type_idx" ON "payments"("user_id", "type");
CREATE INDEX "payments_recipient_user_id_idx" ON "payments"("recipient_user_id");
CREATE INDEX "payments_status_idx" ON "payments"("status");
CREATE INDEX "payments_createdAt_idx" ON "payments"("createdAt");

-- CreateTable: Payout
CREATE TABLE "payouts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "trainer_id" UUID NOT NULL,
    "amount_cents" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'usd',
    "stripe_transfer_id" TEXT,
    "status" "PaymentStatus" NOT NULL DEFAULT 'PROCESSING',
    "period_start" TIMESTAMP(3) NOT NULL,
    "period_end" TIMESTAMP(3) NOT NULL,
    "payment_ids" TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payouts_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "payouts_stripe_transfer_id_key" ON "payouts"("stripe_transfer_id") WHERE "stripe_transfer_id" IS NOT NULL;
CREATE INDEX "payouts_trainer_id_status_idx" ON "payouts"("trainer_id", "status");

-- CreateTable: AiUsageLog
CREATE TABLE "ai_usage_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "feature" "AIFeature" NOT NULL,
    "model" TEXT,
    "prompt_tokens" INTEGER NOT NULL DEFAULT 0,
    "completion_tokens" INTEGER NOT NULL DEFAULT 0,
    "estimated_cost" DECIMAL(10,6) NOT NULL DEFAULT 0,
    "success" BOOLEAN NOT NULL DEFAULT true,
    "error" TEXT,
    "latency_ms" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_usage_logs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ai_usage_logs_user_id_feature_createdAt_idx" ON "ai_usage_logs"("user_id", "feature", "createdAt");
CREATE INDEX "ai_usage_logs_createdAt_idx" ON "ai_usage_logs"("createdAt");

-- CreateTable: AiConversation
CREATE TABLE "ai_conversations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "feature" "AIFeature" NOT NULL DEFAULT 'COACH_CHAT',
    "title" TEXT,
    "history" JSONB NOT NULL DEFAULT '[]',
    "context" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ai_conversations_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ai_conversations_user_id_feature_idx" ON "ai_conversations"("user_id", "feature");

-- CreateTable: AiGeneratedPlan
CREATE TABLE "ai_generated_plans" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "feature" "AIFeature" NOT NULL,
    "payload" JSONB NOT NULL,
    "applied_ref" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_generated_plans_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ai_generated_plans_user_id_feature_idx" ON "ai_generated_plans"("user_id", "feature");

-- CreateTable: WearableDataPoint
CREATE TABLE "wearable_data_points" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "source" "WearableSource" NOT NULL,
    "type" "WearableDataType" NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "value" DECIMAL(12,3) NOT NULL,
    "unit" TEXT NOT NULL,
    "details" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "wearable_data_points_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "wearable_data_points_user_id_type_date_idx" ON "wearable_data_points"("user_id", "type", "date");
CREATE INDEX "wearable_data_points_source_idx" ON "wearable_data_points"("source");

-- CreateTable: AuditLog
CREATE TABLE "audit_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "actor_id" UUID,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT,
    "before" JSONB,
    "after" JSONB,
    "ip" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "audit_logs_actor_id_createdAt_idx" ON "audit_logs"("actor_id", "createdAt");
CREATE INDEX "audit_logs_entity_type_entity_id_idx" ON "audit_logs"("entity_type", "entity_id");

-- CreateTable: PlatformSetting
CREATE TABLE "platform_settings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "platform_settings_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "platform_settings_key_key" ON "platform_settings"("key");

-- CreateTable: AnalyticsCache
CREATE TABLE "analytics_cache" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "scope" TEXT NOT NULL,
    "scope_id" TEXT,
    "payload" JSONB NOT NULL,
    "computed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "analytics_cache_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "analytics_cache_scope_scope_id_key" ON "analytics_cache"("scope", "scope_id");

-- CreateTable: CorporateOrg
CREATE TABLE "corporate_orgs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "admin_user_id" UUID NOT NULL,
    "seats" INTEGER NOT NULL DEFAULT 50,
    "logo_url" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "corporate_orgs_pkey" PRIMARY KEY ("id")
);


-- JoinTable: implicit many-to-many Payment <-> Payout
CREATE TABLE "_PaymentToPayout" (
    "A" UUID NOT NULL,
    "B" UUID NOT NULL
);

CREATE UNIQUE INDEX "_PaymentToPayout_AB_unique" ON "_PaymentToPayout"("A", "B");
CREATE INDEX "_PaymentToPayout_B_index" ON "_PaymentToPayout"("B");

-- AddForeignKey
ALTER TABLE "fitness_profiles" ADD CONSTRAINT "fitness_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "exercises" ADD CONSTRAINT "exercises_submitted_by_id_fkey" FOREIGN KEY ("submitted_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "favorite_exercises" ADD CONSTRAINT "favorite_exercises_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "favorite_exercises" ADD CONSTRAINT "favorite_exercises_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "exercise_ratings" ADD CONSTRAINT "exercise_ratings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "exercise_ratings" ADD CONSTRAINT "exercise_ratings_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "workouts" ADD CONSTRAINT "workouts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "workouts" ADD CONSTRAINT "workouts_parent_workout_id_fkey" FOREIGN KEY ("parent_workout_id") REFERENCES "workouts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "workout_exercises" ADD CONSTRAINT "workout_exercises_workout_id_fkey" FOREIGN KEY ("workout_id") REFERENCES "workouts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "workout_exercises" ADD CONSTRAINT "workout_exercises_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "programs" ADD CONSTRAINT "programs_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "program_workouts" ADD CONSTRAINT "program_workouts_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "program_workouts" ADD CONSTRAINT "program_workouts_workout_id_fkey" FOREIGN KEY ("workout_id") REFERENCES "workouts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "program_enrollments" ADD CONSTRAINT "program_enrollments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "program_enrollments" ADD CONSTRAINT "program_enrollments_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "program_reviews" ADD CONSTRAINT "program_reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "program_reviews" ADD CONSTRAINT "program_reviews_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "program_reviews" ADD CONSTRAINT "program_reviews_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "program_enrollments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "certificates" ADD CONSTRAINT "certificates_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "workout_sessions" ADD CONSTRAINT "workout_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "workout_sessions" ADD CONSTRAINT "workout_sessions_workout_id_fkey" FOREIGN KEY ("workout_id") REFERENCES "workouts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "session_logged_sets" ADD CONSTRAINT "session_logged_sets_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "workout_sessions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "session_logged_sets" ADD CONSTRAINT "session_logged_sets_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "personal_records" ADD CONSTRAINT "personal_records_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "personal_records" ADD CONSTRAINT "personal_records_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "pr_history" ADD CONSTRAINT "pr_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pr_history" ADD CONSTRAINT "pr_history_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pr_history" ADD CONSTRAINT "pr_history_record_id_fkey" FOREIGN KEY ("record_id") REFERENCES "personal_records"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "cardio_sessions" ADD CONSTRAINT "cardio_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cardio_sessions" ADD CONSTRAINT "cardio_sessions_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "routes"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "routes" ADD CONSTRAINT "routes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "foods" ADD CONSTRAINT "foods_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "food_favorites" ADD CONSTRAINT "food_favorites_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "food_favorites" ADD CONSTRAINT "food_favorites_food_id_fkey" FOREIGN KEY ("food_id") REFERENCES "foods"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "recipes" ADD CONSTRAINT "recipes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "recipe_ingredients" ADD CONSTRAINT "recipe_ingredients_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "recipe_ingredients" ADD CONSTRAINT "recipe_ingredients_food_id_fkey" FOREIGN KEY ("food_id") REFERENCES "foods"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "meal_log_entries" ADD CONSTRAINT "meal_log_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meal_log_entries" ADD CONSTRAINT "meal_log_entries_food_id_fkey" FOREIGN KEY ("food_id") REFERENCES "foods"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "meal_log_entries" ADD CONSTRAINT "meal_log_entries_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "water_logs" ADD CONSTRAINT "water_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "nutrition_goals" ADD CONSTRAINT "nutrition_goals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "meal_plans" ADD CONSTRAINT "meal_plans_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "plan_meals" ADD CONSTRAINT "plan_meals_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "meal_plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "meal_plan_follows" ADD CONSTRAINT "meal_plan_follows_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "meal_plan_follows" ADD CONSTRAINT "meal_plan_follows_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "meal_plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "grocery_lists" ADD CONSTRAINT "grocery_lists_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "grocery_lists" ADD CONSTRAINT "grocery_lists_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "meal_plans"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "body_stats" ADD CONSTRAINT "body_stats_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "progress_photos" ADD CONSTRAINT "progress_photos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "progress_photos" ADD CONSTRAINT "progress_photos_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "workout_sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "body_stat_goals" ADD CONSTRAINT "body_stat_goals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_achievement_id_fkey" FOREIGN KEY ("achievement_id") REFERENCES "achievements"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "follows" ADD CONSTRAINT "follows_follower_id_fkey" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "follows" ADD CONSTRAINT "follows_following_id_fkey" FOREIGN KEY ("following_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "posts" ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "posts" ADD CONSTRAINT "posts_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "workout_sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "posts" ADD CONSTRAINT "posts_cardio_id_fkey" FOREIGN KEY ("cardio_id") REFERENCES "cardio_sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "posts" ADD CONSTRAINT "posts_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "routes"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "posts" ADD CONSTRAINT "posts_photo_id_fkey" FOREIGN KEY ("photo_id") REFERENCES "progress_photos"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "posts" ADD CONSTRAINT "posts_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "comments" ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "comments" ADD CONSTRAINT "comments_discussion_id_fkey" FOREIGN KEY ("discussion_id") REFERENCES "group_discussions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "comments" ADD CONSTRAINT "comments_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "kudos" ADD CONSTRAINT "kudos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "kudos" ADD CONSTRAINT "kudos_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "groups" ADD CONSTRAINT "groups_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "group_members" ADD CONSTRAINT "group_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "group_members" ADD CONSTRAINT "group_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "group_discussions" ADD CONSTRAINT "group_discussions_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "group_discussions" ADD CONSTRAINT "group_discussions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "content_reports" ADD CONSTRAINT "content_reports_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "trainer_profiles" ADD CONSTRAINT "trainer_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "trainer_availability" ADD CONSTRAINT "trainer_availability_trainer_id_fkey" FOREIGN KEY ("trainer_id") REFERENCES "trainer_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "trainer_session_bookings" ADD CONSTRAINT "trainer_session_bookings_trainer_id_fkey" FOREIGN KEY ("trainer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "trainer_session_bookings" ADD CONSTRAINT "trainer_session_bookings_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "trainer_clients" ADD CONSTRAINT "trainer_clients_trainer_id_fkey" FOREIGN KEY ("trainer_id") REFERENCES "trainer_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "trainer_clients" ADD CONSTRAINT "trainer_clients_client_user_id_fkey" FOREIGN KEY ("client_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "trainer_clients" ADD CONSTRAINT "trainer_clients_trainer_id_fkey1" FOREIGN KEY ("trainer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "trainer_messages" ADD CONSTRAINT "trainer_messages_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "trainer_session_bookings"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "trainer_messages" ADD CONSTRAINT "trainer_messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "trainer_messages" ADD CONSTRAINT "trainer_messages_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "live_classes" ADD CONSTRAINT "live_classes_trainer_id_fkey" FOREIGN KEY ("trainer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "class_enrollments" ADD CONSTRAINT "class_enrollments_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "live_classes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "class_enrollments" ADD CONSTRAINT "class_enrollments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "class_chat_messages" ADD CONSTRAINT "class_chat_messages_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "live_classes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "class_chat_messages" ADD CONSTRAINT "class_chat_messages_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "challenges" ADD CONSTRAINT "challenges_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "challenges" ADD CONSTRAINT "challenges_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "challenges" ADD CONSTRAINT "challenges_corporate_org_id_fkey" FOREIGN KEY ("corporate_org_id") REFERENCES "corporate_orgs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "challenge_enrollments" ADD CONSTRAINT "challenge_enrollments_challenge_id_fkey" FOREIGN KEY ("challenge_id") REFERENCES "challenges"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "challenge_enrollments" ADD CONSTRAINT "challenge_enrollments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "challenge_enrollments" ADD CONSTRAINT "challenge_enrollments_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "challenge_teams"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "challenge_milestones" ADD CONSTRAINT "challenge_milestones_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "challenge_teams" ADD CONSTRAINT "challenge_teams_challenge_id_fkey" FOREIGN KEY ("challenge_id") REFERENCES "challenges"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "challenge_team_members" ADD CONSTRAINT "challenge_team_members_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "challenge_teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "challenge_team_members" ADD CONSTRAINT "challenge_team_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "scheduled_items" ADD CONSTRAINT "scheduled_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "scheduled_items" ADD CONSTRAINT "scheduled_items_workout_id_fkey" FOREIGN KEY ("workout_id") REFERENCES "workouts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "scheduled_items" ADD CONSTRAINT "scheduled_items_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "live_classes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "scheduled_items" ADD CONSTRAINT "scheduled_items_challenge_id_fkey" FOREIGN KEY ("challenge_id") REFERENCES "challenges"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "scheduled_items" ADD CONSTRAINT "scheduled_items_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "trainer_session_bookings"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "scheduled_items" ADD CONSTRAINT "scheduled_items_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "class_enrollments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "device_tokens" ADD CONSTRAINT "device_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "web_push_subscriptions" ADD CONSTRAINT "web_push_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "payments" ADD CONSTRAINT "payments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_recipient_user_id_fkey" FOREIGN KEY ("recipient_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "trainer_session_bookings"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "live_classes"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "payouts" ADD CONSTRAINT "payouts_trainer_id_fkey" FOREIGN KEY ("trainer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ai_usage_logs" ADD CONSTRAINT "ai_usage_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ai_conversations" ADD CONSTRAINT "ai_conversations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ai_generated_plans" ADD CONSTRAINT "ai_generated_plans_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "wearable_data_points" ADD CONSTRAINT "wearable_data_points_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "corporate_orgs" ADD CONSTRAINT "corporate_orgs_admin_user_id_fkey" FOREIGN KEY ("admin_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "_PaymentToPayout" ADD CONSTRAINT "_PaymentToPayout_A_fkey" FOREIGN KEY ("A") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_PaymentToPayout" ADD CONSTRAINT "_PaymentToPayout_B_fkey" FOREIGN KEY ("B") REFERENCES "payouts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
