/**
 * Schedule service — the calendar / weekly planner. ScheduledItems are
 * generated by program enrollment + manual planning, and can be
 * rescheduled, completed, skipped, or set as rest/deload days.
 */
const prisma = require('../lib/prisma');
const { notFound, badRequest } = require('../utils/response.util');

function startOfDay(d) { const x = new Date(d); x.setHours(0, 0, 0, 0); return x; }
function addDays(d, n) { const x = new Date(d); x.setDate(x.getDate() + n); return x; }

async function add(userId, data) {
  if (!data.date || !data.activityType) throw badRequest('date and activityType required');
  return prisma.scheduledItem.create({
    data: {
      userId,
      date: startOfDay(data.date),
      activityType: data.activityType,
      workoutId: data.workoutId || null,
      programId: data.programId || null,
      classId: data.classId || null,
      challengeId: data.challengeId || null,
      bookingId: data.bookingId || null,
      status: 'PLANNED',
      isDeload: !!data.isDeload,
      note: data.note || null,
    },
  });
}

/** Manual bulk planner — lay out a week in one call. */
async function bulkPlan(userId, { items = [] }) {
  if (!items.length) throw badRequest('No items');
  return prisma.scheduledItem.createMany({
    data: items.map((i) => ({
      userId,
      date: startOfDay(i.date),
      activityType: i.activityType,
      workoutId: i.workoutId || null,
      programId: i.programId || null,
      note: i.note || null,
      isDeload: !!i.isDeload,
      status: 'PLANNED',
    })),
  });
}

async function range(userId, { from, to }) {
  if (!from || !to) throw badRequest('from and to required');
  return prisma.scheduledItem.findMany({
    where: { userId, date: { gte: startOfDay(from), lte: startOfDay(to) } },
    include: { workout: { select: { id: true, name: true, difficulty: true } }, klass: { select: { id: true, title: true, classType: true, status: true } }, booking: { select: { id: true, sessionType: true, status: true, scheduledAt: true } } },
    orderBy: { date: 'asc' },
  });
}

async function week(userId, { startDate }) {
  const start = startOfDay(startDate || new Date());
  const items = await range(userId, { from: start, to: addDays(start, 6) });
  const days = [];
  for (let i = 0; i < 7; i += 1) {
    const d = addDays(start, i);
    days.push({ date: d, items: items.filter((it) => startOfDay(it.date).getTime() === d.getTime()) });
  }
  const summary = {
    planned: items.filter((i) => i.status === 'PLANNED').length,
    completed: items.filter((i) => i.status === 'COMPLETED').length,
    missed: items.filter((i) => i.status === 'MISSED').length,
  };
  return { start, days, summary };
}

async function today(userId) {
  const d = startOfDay(new Date());
  const items = await prisma.scheduledItem.findMany({
    where: { userId, date: d },
    include: { workout: { select: { id: true, name: true, difficulty: true, estimatedDuration: true } }, klass: { select: { id: true, title: true, classType: true, status: true, roomId: true } }, booking: { include: { trainer: { select: { id: true, displayName: true, avatarUrl: true } } } } },
    orderBy: { createdAt: 'asc' },
  });
  return items;
}

async function update(userId, id, data) {
  const item = await prisma.scheduledItem.findFirst({ where: { id, userId } });
  if (!item) throw notFound('Scheduled item not found');
  const patch = {};
  if (data.note !== undefined) patch.note = data.note;
  if (data.isDeload !== undefined) patch.isDeload = data.isDeload;
  if (data.status) patch.status = data.status;
  if (data.date) patch.date = startOfDay(data.date);
  return prisma.scheduledItem.update({ where: { id }, data: patch });
}

async function setStatus(userId, id, status) {
  const item = await prisma.scheduledItem.findFirst({ where: { id, userId } });
  if (!item) throw notFound('Scheduled item not found');
  return prisma.scheduledItem.update({ where: { id }, data: { status } });
}

async function reschedule(userId, id, { date }) {
  const item = await prisma.scheduledItem.findFirst({ where: { id, userId } });
  if (!item) throw notFound('Scheduled item not found');
  return prisma.scheduledItem.update({ where: { id }, data: { date: startOfDay(date), status: 'RESCHEDULED', rescheduledFrom: item.date } });
}

async function remove(userId, id) {
  const item = await prisma.scheduledItem.findFirst({ where: { id, userId } });
  if (!item) throw notFound('Scheduled item not found');
  await prisma.scheduledItem.delete({ where: { id } });
  return true;
}

/** Mark a day fully as rest (adds a REST item, clears planned non-class items). */
async function setRestDay(userId, { date }) {
  const d = startOfDay(date);
  await prisma.scheduledItem.deleteMany({ where: { userId, date: d, activityType: 'WORKOUT', status: 'PLANNED' } });
  const existing = await prisma.scheduledItem.findFirst({ where: { userId, date: d, activityType: 'REST' } });
  if (existing) return existing;
  return prisma.scheduledItem.create({ data: { userId, date: d, activityType: 'REST', status: 'REST_DAY' } });
}

/** Roll unfinished items from a past date to a new date. */
async function rollOver(userId, { fromId, toDate }) {
  const item = await prisma.scheduledItem.findFirst({ where: { id: fromId, userId } });
  if (!item) throw notFound('Scheduled item not found');
  const d = startOfDay(toDate);
  const created = await prisma.scheduledItem.create({ data: { ...item, id: undefined, date: d, status: 'PLANNED', rescheduledFrom: item.date, createdAt: undefined, updatedAt: undefined } });
  await prisma.scheduledItem.update({ where: { id: fromId }, data: { status: 'RESCHEDULED' } });
  return created;
}

/** Upcoming items (next N days) with reminder flag. */
async function upcoming(userId, { days = 7, limit = 50 }) {
  const start = startOfDay(new Date());
  return prisma.scheduledItem.findMany({
    where: { userId, date: { gte: start, lte: addDays(start, days) }, status: 'PLANNED' },
    include: { workout: { select: { id: true, name: true } } },
    orderBy: { date: 'asc' },
    take: limit,
  });
}

module.exports = { add, bulkPlan, range, week, today, update, setStatus, reschedule, remove, setRestDay, rollOver, upcoming };
